export const Types = {
  CHANGE_CHARACTER_PHOTO: 'CHANGE_CHARACTER_PHOTO',
  CHANGE_STATE_POPUP: 'CHANGE_STATE_POPUP',
  CHANGE_SERIAL_DATA: 'CHANGE_SERIAL_DATA',
  CHANGE_CHARACTERS_DATA: 'CHANGE_CHARACTERS_DATA',
  CHANGE_IS_LOADER: 'CHANGE_IS_LOADER',
  CHANGE_ERROR: 'CHANGE_ERROR',
};
